---
- name: Pull and run sql image
  hosts: all
  remote_user: remoteuser
  tasks:
    - name: Pull sql image
      docker_image:
        name: artSale-mysql
        pull: yes

    - name: "Launch database container"
      docker_container:
        name: "artSale-mysql"
        image: mysql:8.0.20
        volumes:
          - "/var/lib/mysql:rw"
        restart: yes
        restart_policy: on-failure
        networks:
          -backend
        exposed_ports:
          - 8091

- name: Pull and run springboot image
  hosts: all
  remote_user: remoteuser
  tasks:
    - name: Pull springboot image
      docker_image:
        name: kanchanmahajan67/spe-spring2:latest
        pull: yes

    - name: Running springboot image
      docker_container:
        name: springboot
        image: kanchanmahajan67/spe-spring2
        state: started
        restart: yes
        restart_policy : on-failure
        env:
          APP_NAME: "app"
          DATABASE_HOST: "artSale-mysql"
        exposed_ports:
          - 8099
        networks:
          - name: backend

- name: Pull and run react image
  hosts: all
  remote_user: remoteuser
  tasks:
    - name: Pull react image
      docker_image:
        name: kanchanmahajan67/spe-react2:latest
        pull: yes

    - name: Running react image
      docker_container:
        name: nginx
        image: kanchanmahajan67/spe_frontend_react_backwofront:latest
        state: started
        restart: yes
        restart_policy : on-failure
        ports:
          - "80
        networks:
          - name: backend


  env:
    MYSQL_ROOT_PASSWORD: GOforkanchu@67!
    MYSQL_DATABASE: art_spe3
    MYSQL_USER: root
    MYSQL_PASSWORD: GOforkanchu@67!
    MYSQL_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/art_spe3?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true

